### ISSUE TITLE
Interesting...

### ISSUE THREAD

**Issue by OneLoneCoder** [gamepopper/KitConsole#2]
Some of that code looks exactly like mine! Even the typos - c'mon man, respect the license...

**Comment by SalmonSan** [comment]
^ I agree with this guy. You deserve none of your followers if you copy code from Javid.

**Comment by UglySwedishFish** [comment]
love this kind of people.

**Comment by Terabyte04** [comment]
What a dickhead, he's not going to admit he stole @OneLoneCoder 's code.

**Comment by AleksandarSherbula** [comment]
Wow, atleast credit the man.

**Comment by iProgramMC** [comment]
Respect the people you've copied code from and credit them for it! At least appreciate what you're leeching off of!

**Comment by dragoneye65** [comment]
The good man has updated the Credit.

"This library was written for use in C/C++ to be mostly header only. A lot of it was inspired by an engine written by OneLoneCoder."

**Comment by OneLoneCoder** [comment]
What a gent.
